services:

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  backend:
    image: tablic-backend:latest
    build: 
      context: ./backend
      args:
        INSTALL_DEV: ${DEVELOPMENT}
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    image: tablic-frontend:latest
    build:
      context: ./frontend
    ports:
      - 80:80


volumes:
  mongo-data:
  mongo-configdb:
