name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing-backend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v2

    - name: Create dotenv file
      run: cp .env.example .env

    - name: Pull the latest image to build
      run: docker-compose pull

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build the image
      run: docker-compose up --build -d

    - name: Run tests
      working-directory: ${{ env.working-directory }}
      run: docker exec tablic-backend pytest --cov=app --cov=tests --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./backend/coverage.xml
